import { RolePage } from "../components/role-page";

export default function AEPage() {
  return <RolePage code="AE" title="Turn a promising event conversation into a real next step." intro="Arrive with a point of view about the account, diagnose before you demo, and leave every serious conversation with a named owner and a scheduled next action." sections={[
    { label: "Before", title: "Build the meeting hypothesis", items: ["Download the event mobile app as soon as attendee access opens. Use it to review attendees, companies, sessions, and meeting opportunities.", "Review the account history, active opportunities, stakeholder map, and previous outreach before every booked or priority meeting.", "Use the SDR’s research to write one hypothesis about why the account may need Simple now and one question that could disprove it.", "Choose the proof that fits the hypothesis: sales-call containment, lower abandonment, faster time to production, or the revenue-to-cost advantage. Do not stack every number into the pitch.", "Prepare the workflow most relevant to the account. For attendee-only events, prepare for a peer conversation rather than promising a live demo that is not available.", "Decide the next step you want before the event starts, including who needs to join and what should be covered."] },
    { label: "On site", title: "Record the useful details", items: ["Add every booked meeting to HubSpot and complete the required meeting details there before the end of the day.", "Take warm SDR handoffs quickly and confirm the person’s role before starting the pitch.", "Ask how inbound calls work today, roughly how many arrive each month, who owns the operation, and what would make a change urgent.", "Use one relevant proof point, then show the part of the product that answers the problem they described.", "Keep Granola on for substantive conversations. Capture the current setup, volume, pain, stakeholders, objections, timing, and decision process.", "Agree on the next action while you are together. Offer two times, send the invite live, and ask the contact to accept it before the conversation ends."] },
    { label: "After", title: "Close the loop with context", items: ["Send a personal follow-up within 24 hours while the conversation is still specific. Reference what they said and make one clear ask.", "For a scheduled demo, create or update the deal in HubSpot, use the correct stage, and record the event source and campaign fields.", "Write a note that lets another teammate continue without asking the contact to repeat the conversation.", "If the account is not ready, record the future trigger and follow-up date instead of sending generic check-ins.", "Hand any SDR or marketing follow-up to a named person with a due date. Do not leave contacts in a shared, unowned queue."] },
  ]} handoff="Record the account context, current setup, call volume, problem, stakeholders, objections, next action, owner, and due date." />;
}
