import { RolePage } from "../components/role-page";

export default function SDRPage() {
  return <RolePage code="SDR" title="Run one event motion across phone, email, and LinkedIn." intro="Build a verified list, find one relevant reason to contact each priority account, and route every response toward an in-person conversation, the teammate attending, or the right owner." sections={[
    { label: "Target", title: "Build the right list", items: [<>Download the event mobile app as soon as attendee access opens. Use attendee names and companies to find and verify work contact details in <a className="inline-link" href="https://app.zoominfo.com/" target="_blank" rel="noreferrer">ZoomInfo ↗</a>.</>, "Combine the event list with likely ICP attendees, warm accounts that have not booked, and active CRM contacts.", <>For vendor-specific events, use <a className="inline-link" href="https://app.zoominfo.com/" target="_blank" rel="noreferrer">ZoomInfo technographics ↗</a> to find companies using that vendor’s technology, then layer in our ICP criteria.</>, "Verify titles and contact details, remove duplicates, and check current ownership before anyone enters a sequence.", "For priority accounts, identify the two to four people involved in contact-center operations, sales operations, CX technology, or the buying decision.", "Find one useful trigger per account—a hiring plan, earnings priority, leadership change, expansion, launch, or technology change. Research should explain why now, not decorate the message."] },
    { label: "Outreach", title: "Use the compressed event sequence", items: ["Use the seven-day event cadence: Day 1 LinkedIn connection and email; Day 2 call; Day 3 LinkedIn message if connected; Day 4 personalized email; Day 6 call; Day 7 close-the-loop email.", "The event is a genuine reason to connect. Keep the connection note short and do not pitch in it.", "Keep the first email focused on their situation, one relevant proof point, and one question. Do not send a calendar link until they respond.", "Match the ask to the activation on the event page: a peer conversation for attendee-only events, or a meeting and live demo when a booth or demo area is available.", "Branch immediately: if they are attending, offer two times; if they are not, ask who from their team is going; if they are the wrong person, ask for the owner and log the referral."] },
    { label: "On site", title: "Qualify and route", items: ["Start with two questions: how inbound calls are handled today, and roughly how many arrive each month.", "Use the field guide as a starting point: 5,000+ monthly calls goes to an AE or live demo; 500–5,000 goes to a post-event call; below 500 gets a friendly close unless the context says otherwise.", "Make a warm handoff to the AE. If the AE is busy, keep the contact engaged, capture a mobile number, and lock a time before they leave.", "Use one proof point that fits what they told you. Do not turn the conversation into a feature list.", <>Before the day ends, add every booked meeting to <a className="inline-link" href="https://app.hubspot.com/" target="_blank" rel="noreferrer">HubSpot ↗</a> with the event source, current setup, call volume, qualification outcome, owner, agreed next action, and meeting logistics.</>] },
    { label: "After", title: "Follow up from what they said", items: ["Merge every lead source, remove duplicates, and assign one owner before follow-up starts.", "Send real conversations a personal note the next day. Refer to their current setup or problem and make one clear calendar ask.", "Follow up once three days later. Move longer-term prospects into the normal nurture motion instead of sending repeated check-ins.", <>In <a className="inline-link" href="https://app.hubspot.com/" target="_blank" rel="noreferrer">HubSpot ↗</a>, create a deal when a demo is scheduled, record the event source and stage, and add enough context for the AE to continue the conversation.</>, "Log referrals, disqualifications, and card-only conversations the same day so no response or lead source disappears."] },
  ]} handoff="Every contact needs a source, current setup, volume, outcome, owner, and next action." />;
}
